# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CPAN-Search-Lite
version:      0.47
version_from: lib/CPAN/Search/Lite/Index.pm
installdirs:  site
requires:
    Archive::Tar:                  1.08
    Archive::Zip:                  1.09
    Compress::Zlib:                0
    Config::IniFiles:              0
    CPAN::DistnameInfo:            0
    DBD::mysql:                    0
    File::Spec:                    0
    File::Temp:                    0
    HTML::TextToHTML:              0
    Locale::Country:               0
    LWP:                           0
    Pod::Select:                   0
    SOAP::Lite:                    0
    Sort::Versions:                0
    XML::Parser:                   2
    YAML:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
